# Site settings
remote_theme: decanus/light
title:       Dean Eigenmann
author:      Dean Eigenmann
description: ""
baseurl:     ""
url:         "https://dean.eigenmann.me"
date_format: "%b %-d, %Y"
header_image: /images/emoji.png
header_pages:
 - blog/index.html

external_headers:
 - link: https://distsys.substack.com/
   title: Newsletter
 - link: https://github.com/decanus
   title: Github
 - link: https://twitter.com/deaneigenmann
   title: Twitter

include:
  - blog

# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-156157914-1

# Preview image for social media aka og:image and twitter:image
post_preview_image: true

# Social icons
twitter_username: DeanEigenmann
email: dean@eigenmann.me

# Build settings
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
paginate_path: "/blog/:num/"

  # https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
